services:
  # AUTH DATABASE
  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: ${POSTGRES_AUTH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
      POSTGRES_DB: ${POSTGRES_AUTH_DB}
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - app-network

  # BONDS DATABASE 
  bonds-db:
    image: postgres:15
    container_name: bonds-db
    environment:
      POSTGRES_USER: ${POSTGRES_BONDS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_BONDS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_BONDS_DB}
    ports:
      - "5434:5432"
    volumes:
      - bonds_data:/var/lib/postgresql/data
    networks:
      - app-network

  # PORTFOLIO DATABASE
  portfolio-db:
    image: postgres:15
    container_name: portfolio-db
    environment:
      POSTGRES_USER: ${POSTGRES_PORTFOLIO_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PORTFOLIO_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PORTFOLIO_DB}
    ports:
      - "5435:5432"
    volumes:
      - portfolio_data:/var/lib/postgresql/data
    networks:
      - app-network

  # AUTH SERVICE
  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    container_name: auth-service
    depends_on:
      - auth-db
    environment:
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_AUTH_USER}
      DB_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
      DB_NAME: ${POSTGRES_AUTH_DB}
      APP_PORT: ${APP_PORT_AUTH}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8001:8001"
    networks:
      - app-network

  # === BONDS SERVICE ===
  bonds-service:
    build:
      context: .
      dockerfile: ./bonds-service/Dockerfile
    container_name: bonds-service
    depends_on:
      - bonds-db
    environment:
      DB_HOST: bonds-db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_BONDS_USER}
      DB_PASSWORD: ${POSTGRES_BONDS_PASSWORD}
      DB_NAME: ${POSTGRES_BONDS_DB}
      APP_PORT: ${APP_PORT_BONDS}
      TOKEN_API_TBANK: ${TOKEN_API_TBANK}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

    ports:
      - "8002:8002"
    networks:
      - app-network

  # === PORTFOLIO SERVICE ===
  portfolio-service:
    build:
      context: .
      dockerfile: ./portfolio-service/Dockerfile
    container_name: portfolio-service
    depends_on:
      - portfolio-db
    environment:
      DB_HOST: portfolio-db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_PORTFOLIO_USER}
      DB_PASSWORD: ${POSTGRES_PORTFOLIO_PASSWORD}
      DB_NAME: ${POSTGRES_PORTFOLIO_DB}
      APP_PORT: ${APP_PORT_PORTFOLIO}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8003:8003"
    networks:
      - app-network

  # === API GATEWAY ===
  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - auth-service
      - bonds-service
      - portfolio-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:8001
      BONDS_SERVICE_URL: http://bonds-service:8002
      PORTFOLIO_SERVICE_URL: http://portfolio-service:8003
      APP_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - app-network
  redis:
    image: redis:7-alpine
    container_name: finiboot-redis
    ports:
      - "6379:6379"
    networks:
      - app-network
volumes:
  auth_data:
  bonds_data:
  portfolio_data:

networks:
  app-network:
