// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bonds": {
            "get": {
                "description": "Возвращает постраничный список всех доступных облигаций",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonds"
                ],
                "summary": "Список всех облигаций",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Номер страницы (по умолчанию 0)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Размер страницы (по умолчанию 10, макс 100)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseBonds"
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/bonds/batch": {
            "post": {
                "description": "Принимает массив ISIN и возвращает список найденных облигаций",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonds"
                ],
                "summary": "Получить несколько облигаций сразу (Batch)",
                "parameters": [
                    {
                        "description": "Список ISIN кодов",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RequestBondBatch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Bond"
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректный JSON",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/bonds/{isin}": {
            "get": {
                "description": "Возвращает подробную информацию об облигации по её уникальному коду ISIN",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonds"
                ],
                "summary": "Получить облигацию по ISIN",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ISIN код (например, RU000A1038V6)",
                        "name": "isin",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Bond"
                        }
                    },
                    "404": {
                        "description": "Облигация не найдена",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Простой пинг для проверки работоспособности API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Проверка доступности сервиса",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Ищет облигации по названию или частичному совпадению",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bonds"
                ],
                "summary": "Поиск облигаций",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Поисковый запрос (минимум 1 символ)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Bond"
                            }
                        }
                    },
                    "400": {
                        "description": "Пустой запрос",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Ошибка сервера",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.RequestBondBatch": {
            "type": "object",
            "properties": {
                "isins": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.ResponseBonds": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Bond"
                    }
                },
                "number": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total_elements": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "models.Bond": {
            "type": "object",
            "properties": {
                "amortization_flag": {
                    "type": "boolean"
                },
                "bond_id": {
                    "type": "integer"
                },
                "bond_type": {
                    "type": "string"
                },
                "buy_available_flag": {
                    "type": "boolean"
                },
                "country_of_risk_name": {
                    "type": "string"
                },
                "coupon_quantity_per_year": {
                    "type": "integer"
                },
                "coupons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Coupon"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "floating_coupon_flag": {
                    "type": "boolean"
                },
                "initial_nominal": {
                    "type": "number"
                },
                "isin": {
                    "type": "string"
                },
                "maturity_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nominal": {
                    "type": "number"
                },
                "perpetual_flag": {
                    "type": "boolean"
                },
                "placement_date": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                },
                "sell_available_flag": {
                    "type": "boolean"
                },
                "state_reg_date": {
                    "type": "string"
                },
                "ticker": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Coupon": {
            "type": "object",
            "properties": {
                "coupon_date": {
                    "description": "дата выплаты",
                    "type": "string"
                },
                "coupon_end": {
                    "type": "string"
                },
                "coupon_id": {
                    "type": "integer"
                },
                "coupon_number": {
                    "type": "integer"
                },
                "coupon_period": {
                    "type": "integer"
                },
                "coupon_start": {
                    "type": "string"
                },
                "coupon_type": {
                    "description": "тип купона",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "figi": {
                    "type": "string"
                },
                "pay_one_bond": {
                    "description": "сумма выплаты на одну облигацию",
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "FiniBoot Bonds Service API",
	Description:      "Сервис для управления и поиска облигаций в системе FiniBoot.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
